### ISSUE TITLE
Support multiple protocols

### ISSUE THREAD

**Issue by duelinmarkers** [bguthrie/shrubbery#1]
For stub, spy, etc. Real records often implement several protocols.

**Comment by bguthrie** [comment]
I agree that this is a shortcoming. I've avoided it for the time being because I have the sense, maybe wrong, that the functions that _use_ records/reifieds don't often need to make use of every protocol implemented. Or am I wrong? Is this a dealbreaker for practical, everyday use?

**Comment by duelinmarkers** [comment]
I agree it would be unusual for an individual dependent to rely on multiple protocol implementations of any dependency.

Where we wanted it was for a "system test" that creates the whole system and just replaces the components that do I/O. Several of those components implement an extra (lifecycle-related) protocol that one dependent uses. For the moment we're just manually reifying, but there are other ways we could work around the issue.

I'd already written stub and call-recorder utilities that each support a single protocol, which I'm still using in some places. Was just hoping maybe you'd already jumped through the hoops to support multiple.

**Comment by bguthrie** [comment]
The biggest drawback to multiple-protocol support with the current syntax is the expectation that the first argument will always be a reference to the desired protocol, e.g. `(spy SomeProto some-impl-record)`. I had considered inferring the protocols from the given impl but there doesn't appear to be an easy way to walk back to a set of relevant Clojure protocols from some given object.

I could imagine resolving it a couple of ways: first, by extending the first argument to allow lists, i.e. `(spy [proto-or-protos impl])`; or second, by switching argument order, e.g. `(spy [impl & protos])`. I initially believed there were compelling reasons to start with the protocol first, but I could be convinced. Any preference? The latter could have some composability advantages.

**Comment by bguthrie** [comment]
And lo, did five months pass, and eventually this issue came to be resolved. v0.3.0 shifts away from macros, and both `stub` and `spy` support multiple protocols. `spy` will attempt to infer all protocols implemented by the given object and proxy them automatically; `stub` accepts a variable number of protocols, each followed by an optional hashmap of implementations.
