### ISSUE TITLE
 Support for spying on namespaced protocols without :refer :all

### ISSUE THREAD

**Issue by rkaercher** [bguthrie/shrubbery#5]
Disclaimer: I might very well be doing it wrong.

When trying to spy on a protocol I usually only require the protocol and not :all from the namespace to avoid pollution of the tests namespace. However, with the current implementation of the spy macro I cannot do this. To clarify, this is how the problem is reproducible:

```Clojure
user> (ns test1)
nil
test1> (defprotocol TestProto (a [this arg]))
TestProto
test1> (ns test2)
nil
test2> (require '[shrubbery.core :as s])
nil
test2> (require 'test1)
nil
test2> (def fake-impl (reify test1/TestProto (a [_ _] :fake)))
#'test2/fake-impl
test2> (s/spy test1/TestProto fake-impl)
CompilerException java.lang.RuntimeException: Unable to resolve symbol: a in this context, compiling:(/tmp/form-init8310557090395405498.clj:1:1)
```

If I require everything from the test1 namespace it works:

```Clojure
test2> (require '[test1 :refer :all])
nil
test2> (s/spy TestProto fake-impl)
#object[test2$eval35584$reify__35585 0x48c2232f "test2$eval35584$reify__35585@48c2232f"]
```

Is there a way to make it work? I.e. by taking the namespace into account or prefixing the methods with a dot when generating the proxy calls in the macro?

**Comment by bguthrie** [comment]
You were not doing it wrong! This was a genuine issue. Fixing it took a fair amount of internal rework but there are now tests to cover this use and it should be resolved in v0.3.0. Sorry it took so long to resolve.
