### ISSUE TITLE
Stubs that throw exceptions

### ISSUE THREAD

**Issue by joelittlejohn** [bguthrie/shrubbery#7]
Very nice library. A function-based mocking utility that relies on polymorphism via protocols (rather than magic var rewriting macros a la Midje) was _exactly_ what I'd been looking for 👍 

One useful feature of using test fakes is that it's usually very easy to test all the various failure cases that a component can produce. I notice that there is currently no way using shrubbery to add a stubbed function that throws an exception.

Do you have any thoughts on if it would be possible to include this? Happy to submit a PR but I thought I'd ask about what you feel is the best approach first.

My first thought was to check whether it was possible to supply a function that would be called to provide the result of a stubbed call, but I see this is explicitly not supported, and I guess this is because of the non-macro approach here which makes delayed evaluation impossible. Do you think that this makes an exception throwing stub impossible with the current approach too?

**Comment by bguthrie** [comment]
Thanks for the compliment! Glad to hear that the approach resonated with you. Apologies for the late response on this; I don't check for new issues as often as I should.

I've been chewing on this for a few days and I think you're right that this needs fixing. I wasn't able to figure out how to allow callers to supply raw functions; under the covers I need to drop down into `eval` territory to reify the protocols, as I'm not aware of any way to do so programmatically, and as a result accepting plain old functions is tricky.

As a result I think this needs a special case. I'll take a poke at it, but any opinions and/or PRs are gratefully accepted.

**Comment by bguthrie** [comment]
I've opened a fix in #8. Comments welcome!

**Comment by joelittlejohn** [comment]
Closed by #8
